# Generated by Django 4.0.2 on 2022-02-19 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', editable=False, max_length=500, unique=True)),
                ('event_name', models.CharField(max_length=256)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('first_year', models.BooleanField()),
                ('second_year', models.BooleanField()),
                ('third_year', models.BooleanField()),
                ('fourth_year', models.BooleanField()),
                ('upload_image', models.ImageField(upload_to='uploads/')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
